[build]
  command = """
    cd ../.. &&
    npm ci &&
    ng run todo-test:build:production &&
    ng run todo-test:server:production &&
    mkdir -p netlify/functions &&
    cp -a dist/todo-test/server/. netlify/functions
  """
  # publish the static files
  publish = "dist/todo-test/browser"

# point Netlify at your SSR + any custom functions in
# websites/todo-test/netlify/functions
[functions]
  directory = "netlify/functions"