[build]
  command = """
    cd ../.. &&
    npm install &&
    npx ng build todo-test --configuration production
  """
  publish = "dist/todo-test"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200