[build]
  command = """
    cd ../.. &&
    npm install &&
    npx ng build enzo-concrete --configuration production
  """
  publish = "dist/enzo-concrete"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200