[build]
  command = """
    cd ../.. &&
    npm install &&
    ng run enzo-concrete:build:production &&
    ng run enzo-concrete:server:production &&
    mkdir -p netlify/functions &&
    cp -a dist/enzo-concrete/server/. netlify/functions &&
    cp -a netlify/functions/*.js netlify/functions
  """
  publish = "dist/enzo-concrete/browser"

[functions]
  directory = "netlify/functions"
