publish = "dist/brettaio/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    # Tells the plugin which Angular project in angular.json to build
    project   = "brettaio"
    # Where the plugin should look for the SSR lambda bundle
    functions = "dist/brettaio/server"
