[build]
  command = """
    cd ../.. &&
    npm ci &&
    ng run brettaio:build:production &&
    ng run brettaio:server:production &&
    mkdir -p netlify/functions &&
    cp -a dist/brettaio/server/. netlify/functions
  """
  # publish the static files
  publish = "dist/brettaio/browser"

# point Netlify at your SSR + any custom functions in
# websites/brettaio/netlify/functions
[functions]
  directory = "netlify/functions"