[build]
  command = """
    cd ../.. &&
    npm install &&
    npx ng build brettaio --configuration production
  """
  publish = "dist/brettaio"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200