[build]
  command = "ng build brettaio --configuration production"
  publish = "../../dist/brettaio/browser"
  functions = "/netlify/functions"

[dev]
  command = "ng serve --project=brettaio"
  targetPort = 4200
